// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH50pc21pFSJil1y23GgbFX2BfjvbuwW8',
    appId: '1:198460282284:web:031af1514f0dafc1435609',
    messagingSenderId: '198460282284',
    projectId: 'yoloapps-mynotes-flutter',
    authDomain: 'yoloapps-mynotes-flutter.firebaseapp.com',
    storageBucket: 'yoloapps-mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroUrbFwCbimUN0n7KNBIbRJamFkbDMlU',
    appId: '1:198460282284:android:8cecea09c7846d5b435609',
    messagingSenderId: '198460282284',
    projectId: 'yoloapps-mynotes-flutter',
    storageBucket: 'yoloapps-mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cQgq27NBxXBAToCoAmraZUbKyR3T5Sw',
    appId: '1:198460282284:ios:628dbb5c81476819435609',
    messagingSenderId: '198460282284',
    projectId: 'yoloapps-mynotes-flutter',
    storageBucket: 'yoloapps-mynotes-flutter.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4cQgq27NBxXBAToCoAmraZUbKyR3T5Sw',
    appId: '1:198460282284:ios:d64e680c99ccf03c435609',
    messagingSenderId: '198460282284',
    projectId: 'yoloapps-mynotes-flutter',
    storageBucket: 'yoloapps-mynotes-flutter.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
